### ISSUE TITLE
Ghost commander

### ISSUE THREAD

**Issue by ctinfty** [bradleysigma/tirules#2]
https://github.com/bradleysigma/tirules/blob/ff44b7e1c6426a8d7a88ff74ef6006f6727f70a6/F_creuss.php#L75-L79

I cannot think of an instance where this note is relevant. I think the mahact example is wrong (at least currently) because there is no active system.

**Comment by bradleysigma** [comment]
I believe the community consensus is that the combat system is treated as the active system (at least until v2.1 is released), otherwise a whole bunch of abilities (such as Yin's Devotion) stop working.
