### ISSUE TITLE
Empyrean Agent

### ISSUE THREAD

**Issue by ctinfty** [bradleysigma/tirules#3]
https://github.com/bradleysigma/tirules/blob/ff44b7e1c6426a8d7a88ff74ef6006f6727f70a6/F_empyrean.php#L63

For what purposes is it a cost?

**Comment by bradleysigma** [comment]
Most other agents are worded as either "you may exhaust this card to..." or "you may exhaust this card; if you do". I wanted to make it clear that Acamar couldn't be used if already exhausted.

**Comment by ctinfty** [comment]
Should we add that to the note then?
`<li>Exhausting Acamar is a cost. The <i>Acamar</i> agent&rsquo;s ability cannot be used if it is exhausted.</li>`
