### ISSUE TITLE
Xxcha Mech clarification

### ISSUE THREAD

**Issue by ctinfty** [bradleysigma/tirules#6]
https://github.com/bradleysigma/tirules/blob/871abf915130fe84370aee70ad0e2b094e76e6dd/F_xxcha.php#L73

I think this could be misread as mechs can't use space cannon while on planets. My suggestion:

`<li>The Xxcha player cannot use the <sc>Space Cannon</sc> ability of their mechs during the <b>Space Cannon Defense</b> step of a tactical action after committing them to planets as the active player.</li>`

**Comment by bradleysigma** [comment]
Fixed with fac4985068526c28ba775977cf60a2cb86ae374c.
