### ISSUE TITLE
Note I on Gravity Rift has been settled by Dane, and differs.

### ISSUE THREAD

**Issue by Urabutbl** [bradleysigma/tirules#8]
Note I states "Moving into a gravity rift will not provide the +1, nor will the ships have to roll for removal.". This is how we played it too, but it was settled by Dane at FFG in an e-mail adressing the question: 

https://boardgamegeek.com/thread/1867132/article/29520444#29520444

As can be seen in the copied e-mail, just moving into the gravity rift does in fact apply the +1 bonus. In essence, once you declare movement through a gravity rift, your ship is given the +1, which means you can move through the system even if your ship only originally had movement enough to reach the gravity rift.

However, the roll for removal takes place as stated, ie. if a ship leaves a gravity rift space.

**Comment by bradleysigma** [comment]
That note is specific to moving _into_ a gravity rift. This is distinct from moving _through_ or _out of_ a gravity rift. Moving _into_ a gravity rift will almost always occur when the gravity rift is the active system. The Dane email is specific to moving _through_. Let me know if there's a clearer wording I should use.
